//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Openus.WinPDFv2.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Openus.WinPDFv2.Languages.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append All Raw to Result PDF.
        /// </summary>
        internal static string AppendAllMenu {
            get {
                return ResourceManager.GetString("AppendAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string DependenciesMenu {
            get {
                return ResourceManager.GetString("DependenciesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the split unit.
        /// </summary>
        internal static string EnterTheSplitUnit {
            get {
                return ResourceManager.GetString("EnterTheSplitUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to open some PDFs..
        /// </summary>
        internal static string FailToOpenSomePdf {
            get {
                return ResourceManager.GetString("FailToOpenSomePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoMenu {
            get {
                return ResourceManager.GetString("InfoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load PDF.
        /// </summary>
        internal static string OpenPdfMenu {
            get {
                return ResourceManager.GetString("OpenPdfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Merged Result PDF.
        /// </summary>
        internal static string PreviewMenu {
            get {
                return ResourceManager.GetString("PreviewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        internal static string Raw {
            get {
                return ResourceManager.GetString("Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw PDF count must grather then 0..
        /// </summary>
        internal static string RawPdfCountZero {
            get {
                return ResourceManager.GetString("RawPdfCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Raw group&apos;s PDF?.
        /// </summary>
        internal static string RemoveAllRawPdf {
            get {
                return ResourceManager.GetString("RemoveAllRawPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Raw PDF.
        /// </summary>
        internal static string RemoveAllRawPdfMenu {
            get {
                return ResourceManager.GetString("RemoveAllRawPdfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Result group&apos;s PDF?.
        /// </summary>
        internal static string RemoveAllResultPdf {
            get {
                return ResourceManager.GetString("RemoveAllResultPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Result PDF.
        /// </summary>
        internal static string RemoveAllResultPdfMenu {
            get {
                return ResourceManager.GetString("RemoveAllResultPdfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result PDF count must grather then 0..
        /// </summary>
        internal static string ResultPdfCountZero {
            get {
                return ResourceManager.GetString("ResultPdfCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Merged Result PDF.
        /// </summary>
        internal static string SaveMergedPdfMenu {
            get {
                return ResourceManager.GetString("SaveMergedPdfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Split Result PDF.
        /// </summary>
        internal static string SaveSplitPdfMenu {
            get {
                return ResourceManager.GetString("SaveSplitPdfMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinPDF v2.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string ToolMenu {
            get {
                return ResourceManager.GetString("ToolMenu", resourceCulture);
            }
        }
    }
}
